### ISSUE TITLE
Definition Integrationstest

### ISSUE THREAD

**Issue by hvwaldow** [fairagro/M4.4_UC6_ARC#10]
+ Mit Ben: Input / Output für Testlauf definieren

**Comment by JensKrumsieck** [comment]
The PlantGro.OUT is the file BL bases his Plots on
https://github.com/fairagro/uc6_csmTools/blob/4a2d4fe9c2cefebd36d1335ed9932022f77a768f/inst/extdata/lte_seehausen/2_sim/PlantGro.OUT

So i think comparing the computed values with the ones from the linked version would make up a good first integration test :)

**Comment by JensKrumsieck** [comment]
Benjamins Repo now contains a CI Pipeline doing a full etl pipeline run and an integration test with some checks on the PlantGro.OUT File. The test checks each of the ~63k values in this file respecting its magnitude.

* Test: https://github.com/fairagro/uc6_csmTools/blob/feature/package_management/tests/testthat/test_pipeline_integration.R
* Pipeline: https://github.com/fairagro/uc6_csmTools/blob/feature/package_management/.github/workflows/ci.yml
* Run: https://github.com/fairagro/uc6_csmTools/actions/runs/10178776651/job/28153091016
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdHR2N2w1dXZ6dXhrZGd1ZHFiYmlhZHpkaW8zaTFvbDQ2MDZtMXF4ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Ll37bXYmQecEdBpmmM/giphy.gif)


Found this interesting tool to test GitHub Actions locally: https://github.com/nektos/act

**Comment by JensKrumsieck** [comment]
The test now is also a separated workflow step. So the workflow is testing itself
