### ISSUE TITLE
Review (test): Reproduce with Podman

### ISSUE THREAD

**Issue by hvwaldow** [fairagro/M4.4_UC6_ARC#22]

**Comment by JensKrumsieck** [comment]
## Steps needed:
### Installation and Config
Installation of podman is needed of course and lingering has to be enabled as suggested by podman warnings if one does try to build a container.
```bash
sudo apt install podman
loginctl enable-linger 1000
```
the pull the base image from docker.io the following was added to the registries file `/etc/containers/registries.conf`
```config
unqualified-search-registries = ["docker.io"]
``` 
### Build and Run
The container can be built successfully and runs without any problems 🐳
```bash
podman build . -t uc6
podman run localhost/uc6
```
