### ISSUE TITLE
Create meta data annotations for the cwl files (perhaps (semi-)automatically)

### ISSUE THREAD

**Issue by JensKrumsieck** [fairagro/M4.4_UC6_ARC#26]

**Comment by JensKrumsieck** [comment]
Example: https://git.nfdi4plants.org/zimmer/TurboIDSampleArc/-/blob/main/workflows/EvalTurboID/TurboIDSampleArc.cwl#L44-122

**Comment by aleidel** [comment]
ARC has its own [namespace](https://github.com/nfdi4plants/ARC_ontology) and [schema](https://raw.githubusercontent.com/nfdi4plants/ARC_ontology/main/ARC_v2.0.owl) but also uses other namespaces/ontologies( e.g. edam ontology (also used in [cwl user guide](https://www.commonwl.org/user_guide/topics/metadata-and-authorship.html) and NCI Thesaurus OBO) for term accession. 
Annotation of term accession in process sequence will be difficult... How to identity operation? Is it possible to automate this or better to ask user what the step is doing to avoid 'guessing' errors? Extract operation info from ARC? Make recommendations? Depends on SciWIn User Interface. How to find an ontology that describes this operation? Check if automated tools exist and test them.

[ontology-mapper](https://github.com/ccb-hms/ontology-mapper): maps terms(string input) to ontology and computes a similarity score. Slow for large ontologies, better to use smaller ontologies. Has option to cache an ontology by providing an URL, e.g. https://edamontology.org/EDAM.owl. Tool can use multiple mappers default is [tf-idf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf)-based mapper  (statistical measure), which is faster than Web API-based mappers ([Zooma](https://www.ebi.ac.uk/spot/zooma/) and [Bioportal](https://bioportal.bioontology.org/annotator)) or Syntactic distance-based mappers (pairwise comparison input string and ontology term slow). Alternative, use REST API of mappers... Still requires info from user about steps and might not always find best ontology, only a recommendation...

Another possibility is to ask for workflow design descriptors in SciWIn GUI similar to swate study design descriptors (search for description and find matching terms from different ontologies). Not really automatic, but users would not have to search different ontologies themselves and there are no 'guessing' errors.

**Comment by hvwaldow** [comment]
# Next step:

## Für input, der für alle steps gilt:

+ --role", type=str, help="Role of workflow creator wegmachen.
+ anderer Input, der für alle steps gilt: Aus config file. `.wfaconfig` (Yaml) (prio 2)
+ alternativ aus investigation.xlsx auslesen (wenn die existiert) (prio 1)
+ Interaktive eingabe (prio 3) mit Möglichkeit zu 1-taste -> defaults (leer lassen wenn nötig)

## Für Beschreibung der Steps: 

+ interaktiv, Möglichkeit zu default, möglichkeit Freitext + Möglichkeit Ontologiesuche.
