### ISSUE TITLE
Record provenance for Workflow Run

### ISSUE THREAD

**Issue by JensKrumsieck** [fairagro/M4.4_UC6_ARC#28]
... after the files are annotated with meta data?
does that change the output??

What is in the files generated via #27 ??

**Comment by aleidel** [comment]
What is in the files generated via https://github.com/fairagro/M4.4_UC6_ARC/issues/27 ??
(The `cwltool --provenance` option uses [BagIt](https://datatracker.ietf.org/doc/html/draft-kunze-bagit-14) a file packaging format for storing and transferring files. Each bag has tags, which are metadata files that facilitate and document the storage and transfer, a payload directory containing the data files (`./run1/data`) and payload manifest that lists each file in the bag along with a checksum. The bagIt information and manifests and the can be found in the `./run1` folder.)
In addition, the following folders can be found in `./run1` 
- `data`: with subfolders containing the input/output data files for the workflow steps in the bagIt packaging format, each data element has a checksum as filename
- `metadata`: with `./logs` subfolder containing engine execution logs and `./provenance` subfolder containing provenance information in various forms: json, jsonld, xml, rdf turtle, rdf n-triples and as provn file. This file contains information about input, output, metadata, workflow steps and process runs (wasStartedBy, wasEndedBy,...). If the workflow has been executed using the above command, it also contains the workflow executor (not the creator!).
- `snapshot`: snapshot of the executed main.cwl workflow
- `workflow`: `packed.cwl`: `cwltool --pack` standalone version of the executed workflow with embedded Dockerfile and R scripts of each step; `primary-job.json`: job input for use with packed.cwl (loaction of files is adapted to correct data folder); `primary-output.json`: description and location of primary output (in data folder)

... after the files are annotated with meta data?/ does that change the output??
There is a `./run1/metadata/provenance` folder with metadata/provenance information about the workflow and the executor (if executed with flags as in https://github.com/fairagro/M4.4_UC6_ARC/issues/27).
If an annotated cwl file is used and cwltool is run with the provenance option as in https://github.com/fairagro/M4.4_UC6_ARC/issues/27, then `./run1/workflow/packed.cwl` will contain the annotated metadata information.
