### ISSUE TITLE
Conventions or Parsing of code?

### ISSUE THREAD

**Issue by JensKrumsieck** [fairagro/M4.4_UC6_ARC#30]
Is parsing of code like done currently feasible?
There are possibly a lot of pitfalls.
How about conventions how the user has to design his file headers? Docstring?
Or like the default php documentations?
```php
<?php
/**
 * database.php
 *
 * Database access
 *
 * @category   CategoryName
 * @package    PackageName
 * @author     Mike
 * @copyright  2013 Mike
 * @license    http://www.php.net/license/3_0.txt  PHP License 3.0
 * @version    CVS: $Id:$
 * @link       http://pear.php.net/package/PackageName
 * @see        NetOther, Net_Sample::Net_Sample()
 * @since      File available since Release 1.2.0
 * @deprecated File deprecated in Release 2.0.0
 */
?>
```

Maybe just using the language default format?

Or shall we tell the user to write Nextflow, CWL, ... by himself??

**Comment by hvwaldow** [comment]
Integration in CLI-Tool?
