### ISSUE TITLE
Workflow in ARC

### ISSUE THREAD

**Issue by hvwaldow** [fairagro/M4.4_UC6_ARC#8]
+ `input.yaml`
+ `u6.cwl`
+ possibly more (`/scripts`...)

requires:
* [x] #4 
* [x] #7 
* [x] #19

**Comment by JensKrumsieck** [comment]
main.cwl:

![](https://raw.githubusercontent.com/fairagro/M4.4_UC6_ARC/main/.github/workflow.svg)

**Comment by JensKrumsieck** [comment]
Tagged the Repo at the commit where this was achieved! 
https://github.com/fairagro/M4.4_UC6_ARC/releases/tag/WorkflowInArc
